from environs import Env

env = Env()
env.read_env()

TURN_LIMIT = env.int("TURN_LIMIT", 1000)
TABLE_ROUND_BONUS = env.int("TABLE_ROUND_BONUS", 100)
PROPERTY_MIN_PRICE = env.int("PROPERTY_MIN_PRICE", 10)
PROPERTY_MAX_PRICE = env.int("PROPERTY_MAX_PRICE", 600)
RENT_MIN_PERCENTAGE = env.int("RENT_MIN_PERCENTAGE", 1)
RENT_MAX_PERCENTAGE = env.int("RENT_MAX_PERCENTAGE", 90)
